### ISSUE TITLE
Track and Re-escape Character References

### ISSUE THREAD

**Issue by chadhietala** [ember-template-lint/ember-template-recast#10]
When we tokenize the `ContentStatements` any character reference is [expanded](https://github.com/tildeio/simple-html-tokenizer/blob/master/tests/tokenizer-tests.ts#L186). This expansion occurs because we create `TextNode`s instead of setting HTML.

We need someway of tracking and mapping this character references so that we can serialize back currently. Otherwise we get issues like https://github.com/dyfactor/dyfactor-plugin-disambiguate-locals/issues/3

**Comment by krisselden** [comment]
@chadhietala do you need to preserve unnecessary ones?

**Comment by krisselden** [comment]
wondering why you need to track them

**Comment by krisselden** [comment]
glimmerjs/glimmer-vm#834 is a fix for the issue in the printer, I don't think it is an issue with recast.
