### ISSUE TITLE
Changing argument values to a string - missing quotes in most cases

### ISSUE THREAD

**Issue by zimmi88** [ember-template-lint/ember-template-recast#111]
Example: https://astexplorer.net/#/gist/ab4426b33ad467bf709a4d565a9f5f90/8e16861ea542af3e564e8e8883f13316694367fb

When changing the value of an argument on an ElementNode, the quotes surrounding the string value aren't added, except in the specific case where the original value was itself a string without any spaces.

**Comment by rwjblue** [comment]
Thank you for reporting!

**Comment by sangm** [comment]
It seems like an issue with regex like most things in life!

https://github.com/ember-template-lint/ember-template-recast/blob/master/src/parse-result.js#L6

This regex doesn't seem to support spaces, so this text:

```
@changeMe="this is not yet changed"
```

will not work, however

```
@alsoChange="nope-this-is-not-changed-either"
```

I'm not sure what the correct path forward as this probably has quite a bit of limitations (multiple lines also may not be supported)

@rwjblue if you have ideas, would love to see how I can help!
