### ISSUE TITLE
Adding prop to empty hash pair appends in wrong location

### ISSUE THREAD

**Issue by zimmi88** [ember-template-lint/ember-template-recast#21]
Recast version: 1.2.4

Not 100% sure if this is an issue with Recast or our methodology for authoring changes. But the general gist is that we're trying to append a property to a hash that doesn't include any nodes at present.

Test case:
```
QUnit.test('adding to empty hash pair works', function(assert) {
  let template = '{{#foo-bar}}Hi there!{{/foo-bar}}';
  let { code } = transform(template, env => {
    let { builders: b } = env.syntax;
    return {
      BlockStatement(ast) {
        ast.hash.pairs.push(b.pair('hello', b.string('world')));
      },
    };
  });

  assert.equal(code, '{{#foo-bar hello="world"}}Hi there!{{/foo-bar}}');
});
```

But... instead of appending where we'd expect it to, it appends it to the start of the file...

```
not ok 24 transform > adding to empty hash pair works
  ---
  message: "failed"
  severity: failed
  actual: "hello=\"world\"{{#foo-bar}}Hi there!{{/foo-bar}}"
  expected: "{{#foo-bar hello=\"world\"}}Hi there!{{/foo-bar}}"
  stack:     at Object.<anonymous> (/path/to/ember-template-recast/tests/index-test.js:318:12)
  ...
```

This appears to be due to the fact that, since the hash is empty, its location is "synthetic", and thus its starting location is at the very start of the file.

I've also tried changing the test case so that the transform function returns an entirely newly built block. This works when the contents of the block are really simple, but it breaks down if the block contains complex content, or if you also want to make changes to the subnode as well. Specifically...

- It appears that returning a newly built block causes Recast to traverse the node again. (This is resolved in the code below by attaching a `_gen` property to created nodes.)
- Changes to the inner node appear to get lost.
- There's leftover gobbledygook at the end of the string.

```
QUnit.test('adding to empty hash pair works', function(assert) {
    let template = '{{#foo-bar as |baz|}}{{#baz.blah}}Hello world!{{/baz.blah}}{{/foo-bar}}';
    let { code } = transform(template, env => {
      let { builders: b, traverse: t } = env.syntax;
      return {
        BlockStatement(ast) {
          if (ast.path.original === 'foo-bar' && !ast._gen) {
            console.log('visiting foo-bar');

            t(ast.program, {
              BlockStatement(subAst) {
                if (subAst._gen) {
                  return subAst;
                }
                console.log(`visiting subnode ${subAst.path.original}`);
                return Object.assign(
                  {},
                  { _gen: true },
                  b.block(
                    subAst.path,
                    subAst.params,
                    b.hash([b.pair('hello', b.string('world'))]),
                    subAst.program
                  )
                );
              },
            });

            return Object.assign(
              {},
              { _gen: true },
              b.block(
                ast.path,
                ast.params,
                b.hash([b.pair('hello', b.string('world'))]),
                ast.program
              )
            );
          }
        },
      };
    });

    assert.equal(
      code,
      '{{#foo-bar hello="world" as |baz|}}{{#baz.blah hello="world"}}Hello world!{{/baz.blah}}{{/foo-bar}}'
    );
  });
```
```
not ok 24 transform > adding to empty hash pair works
  ---
  message: "failed"
  severity: failed
  actual: "{{#foo-bar hello=\"world\" as |baz|}}{{#baz.blah}}Hello world!{{/baz.blah}}{{/foo-bar}}}}{{/foo-bar}}"
  expected: "{{#foo-bar hello=\"world\" as |baz|}}{{#baz.blah hello=\"world\"}}Hello world!{{/baz.blah}}{{/foo-bar}}"
  stack:     at Object.<anonymous> (/path/to/ember-template-recast/tests/index-test.js:362:12)
  ...
```

So, with all that said...

1) Is there a recommended pattern for adding hash pairs to hashes that are empty?
2) Do we need to add special logic to handle adding items to an empty hash?

In parallel, I'll investigate and try to put together a PR that would resolve the first test case above in `ember-template-recast`.

Thanks!

**Comment by rwjblue** [comment]
I do think we should make the first test case work, I think we can probably correct the fact that the hash is `(synthetic)` (by actually giving empty hashes a valid location where the start/end are the same).

**Comment by zimmi88** [comment]
Having dug into this a bit more, I'm starting to think this is something that `ember-template-recast` should handle (as opposed to updating `@glimmer/syntax` to report locations for empty hashes).

Take the case of a BlockStatement with a non-existent hash...

```
{{#foo-bar}}{{/foo-bar}}
```

Say we updated this so the hash starts after the "r" in "foo-bar", at line 0, column 10 (0:10) and ends at 0:10. We'd _still_ need special logic in recast to catch this case and add a space between the path and the hash. Else, the end result will be inaccurate.

Does this approach open the library up to having to write more whack-a-mole logic to catch weird edge cases like this, though...? That might just be the nature of a template rewriter such as this. =/

**Comment by rwjblue** [comment]
I think this is fixed now, can you confirm?

**Comment by zimmi88** [comment]
Fixed by https://github.com/ember-template-lint/ember-template-recast/pull/22.

(Sorry, didn't link the two issues together. T_T)
