### ISSUE TITLE
Self-closing tags are broken

### ISSUE THREAD

**Issue by Turbo87** [ember-template-lint/ember-template-recast#23]
<img width="1043" alt="Bildschirmfoto 2019-05-07 um 10 21 36" src="https://user-images.githubusercontent.com/141300/57284663-eed57680-70b1-11e9-9d09-23cf22e6bb3c.png">

**Comment by rwjblue** [comment]
@Turbo87 - This requires the updates you made to glimmer-vm right? Mind cross linking?

**Comment by Turbo87** [comment]
yes, https://github.com/glimmerjs/glimmer-vm/pull/941 is probably related, but I suspect that we need further changes in this project here to fix this bug
