### ISSUE TITLE
Define quotes when generating AttrNode (and probably others)

### ISSUE THREAD

**Issue by jjaffeux** [ember-template-lint/ember-template-recast#267]
Hi,

i'm writing a rule fixer for ember-template-lint and I can't find a way to force the type of quotes used when generating my attribute:
```
builder.attr('foo', builder.text('bar'));
```

Will generate something like:
```
foo="bar"
```

How could I specify it should generate:
```
foo='bar'
```

Reading the code it doesn't seem like it's currently supported, am I wrong? Thanks.

**Comment by rwjblue** [comment]
You are correct, there is no way to use the builder to produce the correct quoting. Though you could use something akin to what I did in https://github.com/ember-template-lint/ember-template-recast/pull/254.

**Comment by MichalBryxi** [comment]
Bumped into this while trying to do something similar. In my case I completely rebuilt class attribute by overwriting the respective `.attribute[x]` with output from `builder.attr(...)`.

I wanted to make sure that the quotes are the same that were used before.

Is this just a missing feature or something that is not supported by principle?
