### ISSUE TITLE
Printing bug, attributes' quotes are doubled on the ends

### ISSUE THREAD

**Issue by NullVoxPopuli** [ember-template-lint/ember-template-recast#319]
ast explorer: https://astexplorer.net/#/gist/ad259df1c5b83be471ec178a46eb4c96/1d70c75ee6692754a1cc0c994e8ac642af2feb1e
and a minimum reproduction demonstrating that, in the console.log, all line/columns are the same:
https://astexplorer.net/#/gist/ad259df1c5b83be471ec178a46eb4c96/fc04c74ce59df8d1e96eb5961b90e1aa2fbf4c3a

(I know the ast explorer version is old, but this same issue happens locally with latest ember-template-lint, too)

```hbs
class="name {{if this.cond "foo"}}" 
```
becomes
```
class=""name {{if this.cond "foo"}}""
```

**Comment by rwjblue** [comment]
Thanks for reporting! I moved this to ember-template-recast for now, though we'll have to see if this is an issue here or in glimmer-vm itself (tbh, I'm not certain).

**Comment by kamal** [comment]
This looks similar to the issue I was able to reproduce in https://github.com/ember-template-lint/ember-template-recast/pull/371 but I found that it's only triggered when a mutation happens

**Comment by kamal** [comment]
I reproduced this issue in https://github.com/ember-template-lint/ember-template-recast/pull/477 which is closer to the original report

**Comment by dcyriller** [comment]
I opened https://github.com/ember-template-lint/ember-template-recast/pull/555 to fix this issue. The fix won't cover https://github.com/ember-template-lint/ember-template-recast/pull/371 though
