### ISSUE TITLE
Out of Memory issues

### ISSUE THREAD

**Issue by rwjblue** [ember-template-lint/ember-template-recast#352]
After #303, running ember-template-lint across a repo with many templates often results in out of memory errors.

I've noticed this in a couple large repos that I help maintain, pinning (often via resolutions) to 4.1.4 is a work around currently.

**Comment by Alonski** [comment]
For context:
An app with 1142 template files I get around 1500MB memory usage.
Recorded like this:
Added this after this line: https://github.com/ember-template-lint/ember-template-lint/blob/master/bin/ember-template-lint.js#L245
```js
    const used = process.memoryUsage().heapUsed / 1024 / 1024;
    console.log(`The script uses approximately ${used} MB`);
```

**Comment by gmurphey** [comment]
Have seen similar in our monorepo (~48k files 😱 ) using node@12.8.3. Noticed that upgrading to node@^14 alleviates the issue. Our current workaround is to lint each package separately. Can confirm that 4.1.3 does not have this issue. Appreciate all you do!

**Comment by dcyriller** [comment]
Sorry for that @rwjblue, let me know if I can help.

**Comment by rwjblue** [comment]
Thanks for fixing @dcyriller!
