### ISSUE TITLE
Textarea doesn't retain whitespace in children

### ISSUE THREAD

**Issue by kamal** [ember-template-lint/ember-template-recast#363]
It appears that newlines inside textearea children are being stripped. I added a failing test to illustrate this issue https://github.com/ember-template-lint/ember-template-recast/pull/359

**Comment by rwjblue** [comment]
Thanks for reporting! This is directly caused by the changes over in https://github.com/tildeio/simple-html-tokenizer/pull/59 which was done to match spec behavior while actually rendering.

**Comment by rwjblue** [comment]
I took another crack at fixing that issue https://github.com/tildeio/simple-html-tokenizer/pull/90

**Comment by rwjblue** [comment]
The fix for this is released in 4.2.1.
