### ISSUE TITLE
Types not published?

### ISSUE THREAD

**Issue by bmish** [ember-template-lint/ember-template-recast#390]
With the conversion to TypeScript in https://github.com/ember-template-lint/ember-template-recast/pull/255, I was hoping type information would be published for consumers of the package, particularly for usages such as this:

```
import { parse } from 'ember-template-recast';
```

So far, I do not see any type information included in the published package for 4.3.0 or 5.0.0.

@rwjblue

**Comment by bmish** [comment]
Adding `"declaration": true` to tsconfig.json should fix this?

**Comment by rwjblue** [comment]
bah, sorry @bmish 🤦

**Comment by rwjblue** [comment]
> I was hoping type information would be published for consumers of the package

Yes, this was exactly my goal (along with finding a non-trivial number of mistaken assumptions while converting 😝 ).
