### ISSUE TITLE
Request new version/release

### ISSUE THREAD

**Issue by MelSumner** [ember-template-lint/ember-template-recast#669]
Requesting a new version/release, as recently merged changes would resolve some issues this package is causing in `ember-template-lint`. 

Thank you!

**Comment by dcyriller** [comment]
Next release will be a new major! It will include the [bump of @glimmer/syntax](https://github.com/ember-template-lint/ember-template-recast/pull/627). Have you seen [this comment](https://github.com/ember-template-lint/ember-template-recast/pull/401#issuecomment-926404384)? It gives an idea of the changes we will have to make in template-lint to use the latest @glimmer/syntax.

The drop of Node 10 opens the way [to publishing ESM modules](https://github.com/ember-template-lint/ember-template-recast/pull/668). I would be in favor of merging the migration to ESM before cutting a release, to group the breaking changes in one major. Does it sound good to you?

This new release will also probably include a new feature:  [allow updating quoteType and isValueless of AttrNodes, and quoteType of StringLiterals](https://github.com/ember-template-lint/ember-template-recast/pull/653) and a few bug fixes (https://github.com/ember-template-lint/ember-template-recast/pull/665, https://github.com/ember-template-lint/ember-template-recast/pull/589, https://github.com/ember-template-lint/ember-template-recast/pull/588, https://github.com/ember-template-lint/ember-template-recast/pull/95).

**Comment by MelSumner** [comment]
@dcyriller it seems sensible; I think the risk here is that folks are sitting with broken linters and there's no real ETA on a fix. I know we avoid ETAs but perhaps we can think about a backup plan, too.

**Comment by dcyriller** [comment]
[v6 is released](https://github.com/ember-template-lint/ember-template-recast/releases/tag/v6.0.0) 🎉

**Comment by dcyriller** [comment]
Closing for https://github.com/ember-template-lint/ember-template-lint/pull/2172
