### ISSUE TITLE
Empty string values return invalid conversion

### ISSUE THREAD

**Issue by tylerturdenpants** [ember-template-lint/ember-template-recast#80]
One of the tests from https://github.com/ember-codemods/ember-angle-brackets-codemod/

Before `ember-template-recast` (correct)
```hbs
input: {{foo/bar name=""}}
output: <Foo::Bar @name="" />
```

After `ember-template-recast` refactor (incorrect)
```hbs
input: {{foo/bar name=""}}
output: <Foo::Bar @name= />
```

**Comment by rwjblue** [comment]
Mind making a failing test for this? I think something akin to

https://github.com/ember-template-lint/ember-template-recast/blob/14f1ef9d8ff74cfec796050e3886fe859baa175f/tests/parse-result-test.js#L41-L53

```js
    QUnit.test('adding attribute with an empty string value', function(assert) {
      let template = `<Foo></Foo>`;

      let ast = parse(template);
      ast.body[0].attributes.push(builders.attr('@name', builders.string('')));

      assert.equal(
        print(ast),
        stripIndent`
        <Foo @name=""></Foo>`
      );
    });
```

---

I'm not 100% sure what the right path forward is here. Specifically, for an `ElementNode` we can not easily determine the difference between `<input disabled>` and `<input value="">` (both are represented in the AST as `AttrNode`s with an empty string as the value).

**Comment by tylerturdenpants** [comment]
This is working now.  Some changes were needed when moving from glimmer printer/parse/transform to ember-template-recast
