### ISSUE TITLE
Self Closing tags 

### ISSUE THREAD

**Issue by tylerturdenpants** [ember-template-lint/ember-template-recast#81]
One of the tests from https://github.com/ember-codemods/ember-angle-brackets-codemod/

Before `ember-template-recast` (correct)
```hbs
input: {{some-component selected=(is-equal this.bar null)}}
output: <SomeComponent @selected={{is-equal this.bar null}} />
```

After `ember-template-recast` refactor (incorrect)
```hbs
input: {{some-component selected=(is-equal this.bar null)}}
output: <SomeComponent @selected={{is-equal this.bar null}}></SomeComponent>
```

**Comment by rwjblue** [comment]
FWIW, we key the self closing tags off of `selfClosing` property on the `ElementNode`. Can you confirm that ember-angle-brackets-codemod sets that flag?

**Comment by tylerturdenpants** [comment]
I have since fix this on the codemod side.

**Comment by NullVoxPopuli** [comment]
no-implicit-this is encountering this issue -- I don't quite understand what's going on, cause `ElementNode` doesn't have a transform
```ts
  let paramTracker = {
    enter(node) {
      node.blockParams.forEach(param => {
        scopedParams.push(param);
      });
    },

    exit(node) {
      node.blockParams.forEach(() => {
        scopedParams.pop();
      });
    },
  };

  return {
    Program: paramTracker,
    ElementNode: paramTracker,
    // etc
```

**Comment by tylerturdenpants** [comment]
@NullVoxPopuli it’s on a PR for the recast refactor.
