### ISSUE TITLE
Order of ops on hash pair generates different results

### ISSUE THREAD

**Issue by zimmi88** [ember-template-lint/ember-template-recast#86]
Example: https://astexplorer.net/#/gist/0649af501602303c1adece7824b5bb14/48929f5cf2838d9e02164b08c1bced29302c5ec3
Using version 3.1.1.

In the above example, the following operations on a given Hash creates the correct output…

- Change a hash pair’s value.
- Add a hash pair.
- Remove a hash pair.

But… change the order and the output is incorrect…

- Remove a hash pair.
- Change a hash pair’s value.
- Add a hash pair.

This appears to hold true for both MustacheStatements and BlockStatements.

EDIT: Updated link at top to a specific revision of the gist. Going to keep experimenting with different methods for writing and orders of operations to see what works and what doesn’t. Latest revision is at https://astexplorer.net/#/gist/0649af501602303c1adece7824b5bb14/latest.

**Comment by rwjblue** [comment]
Thank you for reporting! Will be digging into this this week, hopefully easy to fix but its not quite obvious to me what is going on yet. The AST explorer demo is very helpful.

**Comment by rwjblue** [comment]
I think this was fixed by https://github.com/ember-template-lint/ember-template-recast/pull/90, but working up some tests to confirm/deny.

**Comment by rwjblue** [comment]
Yep, confirmed. Added some more smoke tests in https://github.com/ember-template-lint/ember-template-recast/pull/93, and confirmed they failed in v3.1.1 and pass now in v3.1.3.

**Comment by zimmi88** [comment]
Awesome, thanks for investigating and fixing!
